# версия docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    # volume и связанная с ним директория в контейнере
    environment:
      - POSTGRES_PASSWORD=dima_postgres
    volumes:
      - db_data:/var/lib/postgresql/data/

  bot:
    image: alesha










volumes:
  db_data: